# -*- coding: utf-8 -*-
"""LeNet5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4Cbib31_d_q_g68Beb32qKrQLOgwu01
"""

# Commented out IPython magic to ensure Python compatibility.
#TensorFlow version check
# %tensorflow_version 2.x 

#Load TensorBoard notebook extension
# %load_ext tensorboard

#Print version 
import tensorflow as tf
print(tf.__version__)

# Date & Time library 
import datetime

# Multi dimensional arrays 
import numpy      as np
import tensorflow as tf

# Plotting library 
import matplotlib.pyplot as plt

# Keras is deep learning API written in Python 
from tensorflow.keras        import Model      #Keras graph model 
from tensorflow.keras.models import Sequential #Keras model sequential stack  
from tensorflow.keras.losses import categorical_crossentropy  #Keras loss function  
from tensorflow.keras.layers import Dense, Flatten, Conv2D, AveragePooling2D

from tensorflow.keras       import datasets       # Keras dataset
from tensorflow.keras.utils import to_categorical 

#from __future__ import absolute_import, division, print_function, unicode_literals

# Load MNIST dataset 60K+10K 28x28 gray-scale images of fashion categories 
# This set return a tuple of Numpy arrays for training data & tests data  
(x_train, y_train), (x_test, y_test) = datasets.fashion_mnist.load_data()

#x_train[i] is 28x28 unit8 arrays of fashion image 
#y_train[0] is label for each image

#Labels list 
# 0	T-shirt/top
# 1	Trouser , 2	Pullover , 3	Dress
# 4	Coat    , 5	Sandal   , 6	Shirt
# 7	Sneaker , 8	Bag      , 9	Ankle boot

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print(x_train[0].shape, 'image shape')
#print (x_train[0])

# Add a new axis
x_train = x_train[:, :, :, np.newaxis]
x_test  = x_test [:, :, :, np.newaxis]

print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print(x_train[0].shape, 'image shape')

print (y_train)

# Convert class vectors to binary class matrices.
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test  = to_categorical(y_test, num_classes)

# Binary classifiers defines probability for each element 
# 9 => [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
#print (y_train.shape)

# Data normalization (All values fail between 0..1)
x_train  = x_train.astype('float32')
x_test   = x_test.astype('float32')
x_train /= 255
x_test  /= 255

"""![LeNet-5](http://media5.datahacker.rs/2018/11/LeNet5-1024x188.png)"""

# LeNet-5 model
class LeNet(Sequential):
  def __init__(self, input_shape, nb_classes):
    super().__init__()

    self.add(Conv2D(6, kernel_size=(5, 5), strides=(1, 1), activation='tanh', input_shape=input_shape, padding="same"))
    self.add(AveragePooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid'))
    self.add(Conv2D(16, kernel_size=(5, 5), strides=(1, 1), activation='tanh', padding='valid'))
    self.add(AveragePooling2D(pool_size=(2, 2), strides=(2, 2), padding='valid'))
    self.add(Flatten())
    self.add(Dense(120, activation='tanh'))
    self.add(Dense(84, activation='tanh'))
    self.add(Dense(nb_classes, activation='softmax'))

    self.compile(optimizer='adam',
                loss=categorical_crossentropy,
                metrics=['accuracy'])

model = LeNet(x_train[0].shape, num_classes)

model.summary()

# Place the logs in a timestamped subdirectory
# This allows to easy select different training runs
# In order not to overwrite some data, it is useful to have a name with a timestamp
log_dir="logs\\fit\\" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
# Specify the callback object
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

# tf.keras.callback.TensorBoard ensures that logs are created and stored
# We need to pass callback object to the fit method
# The way to do this is by passing the list of callback objects, which is in our case just one

model.fit(x_train, y=y_train, 
          epochs=20, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback],
          verbose=1)

# Commented out IPython magic to ensure Python compatibility.
# %tensorboard --logdir logs/fit

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat',
               'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

prediction_values = model.predict_classes(x_test)

# set up the figure
fig = plt.figure(figsize=(15, 7))
fig.subplots_adjust(left=0, right=1, bottom=0, top=1, hspace=0.05, wspace=0.05)

# plot the images: each image is 28x28 pixels
for i in range(50):
  ax = fig.add_subplot(5, 10, i + 1, xticks=[], yticks=[])
  ax.imshow(x_test[i,:].reshape((28,28)),cmap=plt.cm.gray_r, interpolation='nearest')
  
  if prediction_values[i] == np.argmax(y_test[i]):
    # label the image with the blue text
    ax.text(0, 7, class_names[prediction_values[i]], color='blue')
  else:
    # label the image with the red text
    ax.text(0, 7, class_names[prediction_values[i]], color='red')

"""---"""